### PR TITLE
Adding host-socket stress parameter

### PR DESCRIPTION
**Pull request by Vr00mm**
Signed-off-by: Remi Ziolkowski <remi.ziolkowski-ext@pole-emploi.fr>

Hello @alexei-led,
Here is the merge request that add the host-socket parameter to stress command.

Best Regards,
Vr00mm

### CODE REVIEW

**Comment by alexei-led** [comment]
Ok, waiting for the fix

**Comment by alexei-led** [comment]
Thank you for the PR. I'm will be able to review it in a week.

**Comment by Vr00mm** [comment]
> Ok, waiting for the fix

Well, I have no idea how to fix it ....
I dont understand the mechanism of the function.

Can we schedule a meet ? Or slack exchange to talk about ?
I need some help...

No problem :) Sorry to bother you in holiday :P

Best Regards
Vr00mm :car:

**Comment by alexei-led** [comment]
closing it for now

**Pull request closed without merging**
